import random

Fact = ["The world’s first motel is in San Luis Obispo, which was built in 1925. When opened, it cost $1.25 for a two-room bungalow with a kitchen and a private adjoining garage.",
"Scotland was one of the few countries able to hold off being conquered by the Romans in the first century A.C.",
"I Will Always Love You was originally written and recorded in 1973 by Dolly Parton. It was written as a farewell to her mentor of seven years.",
"“Opposites attract” is a common myth. People are actually attracted to people who look like family members or those with a similar personality type.",
"Llamas can be used as guards against coyote attacks on sheep herds. Studies have proven that just one guard llama is an effective protector and can even kill the attacking coyotes.",
"The unique smell of rain actually comes from plant oils, bacteria, and ozone.",
"Vanilla flavoring is sometimes made with the urine of beavers.",
"If you heat up a magnet, it will lose its magnetism.",
"The most expensive virtual object is “Club NEVERDIE” in the Entropia Universe which is worth $635,000. It was originally bought at $10,000.",
"Cruise ships have morgues that can store up to 10 bodies at once. The average amount of people that die on cruise ships per year is 200.",
"Birds are the closest living relatives of crocodilians, as well as the descendants of extinct dinosaurs with feathers. This makes them the only surviving dinosaurs.",
"Small as they may be, ladybugs have a unique smell that humans are incredibly sensitive to.",
"During WWII, a U.S. naval destroyer won a battle against a Japanese submarine by throwing potatoes at them. The Japanese thought they were grenades.",
"The Marshal Mathers foundation for at-risk and disadvantaged youth was founded by Eminem.",
"A man with severe OCD and a phobia of germs attempted to commit suicide with a gun to his head. Instead of killing him, the bullet eliminated his mental illness without any other damage.",
"Since 1955, 50% of the population of Niger is consistently under 16 years old. The total current population is 21,600,000.",
"The author of Mary Had a Little Lamb, Sarah Josepha Hale, is most responsible for the creation of Thanksgiving being a national holiday.",
"The oldest unopened bottle of wine was found in a Roman tomb that is over 1,650 years old.",
"Chicken Run is the highest-grossing stop motion animated film, even beating The Nightmare Before Christmas.",
"Nobody knows how the Academy Awards came to be referred to as the Oscars. The earliest mention was 1932, and was made official in 1939.",
"More tornadoes occur in the United Kingdom per square mile than any other country in the world.",
"Owners of personalized license plates in Uganda are facing a tax increase of over 300%, which will raise the tax from $1,498 to $5,992.",
"Popularized by the Shakespeare play, many people think Julius Caesar’s last words were “And you, Brutus?” In reality, he said “You too, my child?”",
"Times Square was originally called Longacre Square until it was renamed in 1904 after The New York Times moved its headquarters to the newly built Times Building.",
"Daniel Craig was an anonymous Storm Trooper in Star Wars: The Force Awakens. Originally, he denied his cameo and claimed he wouldn’t bother being an extra in a movie.",
"Queen Elizabeth has a personal net worth of 425 million dollars. That includes the $65 million Sandringham House and $140 million Balmoral Castle.",
"Although there is currently no drug proven to make someone tell the truth, some countries like Russia, Canada, and India use truth serums.",
"Only primates, humans, and opossums have opposable thumbs. Out of these, the opossum is the only one with no thumbnail.",
"One of the World Trade Center’s was built to be 1,776 feet tall on purpose to reference the year the Declaration of Independence was signed.",
"The word “kimono”, literally means a “thing to wear”. Ki is “wear”, and mono is “thing”.",
"There is a statue of Tesla in Silicon Valley that radiates free Wi-Fi. It was done as an homage to his vision for wireless communication.",
"It snows metal on planet Venus! There are two types that have been found, galena and bismuthinite.",
"Tic Tacs got their name from the sound they make when they are tossed around in their container.",
"Only official members of federally accepted Native American tribes may legally possess or collect eagle feathers. If a normal citizen has one, it is illegal.",
"By the time they have been retired for 2 years, 78% of former NFL players have gone bankrupt or are under financial stress because of joblessness or divorce.",
"500 seeds of 5 different types of seeds were taken into orbit around the moon and later planted around the U.S. as well as a few countries. They were called Moon Trees.",
"In order to protest the high tariffs enforced by a U.K. censorship board, a filmmaker sent in a 10-hour “movie” of white paint drying. They had to watch the entire film.",
"The popular LMFAO group who created the viral hit, Party Rock Anthem, is made up of an uncle-nephew duo.",
"50% of apartments in Los Angeles don’t come with a fridge. This is legal, as fridges are considered an “amenity”, and therefore landlords are not required to provide one.",
"Norway has a 25-year statute of limitation on murder. This means if the murder happened more than 25 years ago, they cannot be charged.",
"Several of the facts on Snapple caps have been found to be outdated, incorrect or exaggerated.",
"Both of the drummers from Queen and Duran Duran had the same name – Roger Taylor.",
"There is a company in the U.K. that offers “being hungover” as a valid reason for calling off work. They are allotted four hungover days per year.",
"The majority of blind people in the U.S. and the U.K. cannot read braille. Statistically, less than 1% of blind in the U.K., and under 10% in the U.S.",
"It’s not just humans who are right or left-handed. Most female cats prefer using their right paw and males are more likely to be left-pawed.",
"Over 290 people have died climbing Mount Everest since 1922. Most deaths occur because of avalanches, and not all bodies have been recovered.",
"There are only two countries in the world that have the color purple in their flags: Nicaragua and Dominica.",
"A bolt of lightning can reach 53,540 degrees Fahrenheit. That’s 5 times hotter than the surface of the sun, which is 10,340 degrees Fahrenheit.",
"There is a village in Russia called Tsovkra where every resident can tightrope walk. It is a tradition that dates back over 100 years but no one knows how it started.",
"When Shakira was in second grade, she was rejected by the school choir because her vibrato was too strong. The music teacher told her that she sounded like a goat.",
"Four of the top seven highest-grossing films of all time were released in 2015. Avengers: Age of Ultron, Furious 7, Jurassic World, and Star Wars: The Force Awakens.",
"Four Nile crocodiles have been found in Florida. They are the second-largest crocodile and are more dangerous than the native crocodiles and alligators in Florida.",
"Julius Caesar’s only son, Caesarion, was the last Pharaoh of Egypt. Even though Cleopatra swears he is Caesar’s son, Caesar never officially acknowledged him.",
"The quietest room in the world in Minnesota is measured in negative decibels – so quiet that you can hear your own heartbeat and your bones moving.",
"“Tsundoku” is a Japanese word for the habit of buying too many books, letting them pile up in your house, and never reading them.",
"The Guinness World Record for the time longest spend searching for the Loch Ness Monster is held by Steve Feltham who camped at Loch Ness for 25 years.",
"Brain fibers lose 10% of their total length every decade. They can shrink even more so under acute stress.",
"Chewing gum boosts mental proficiency and is considered a better test aid than caffeine – but nobody knows why.",
"Per capita, the happiest countries in the world also rank highest in terms of consumers of antidepressants.",
"Even though Irish is the official language of Ireland, Polish is more widely spoken.",
"There’s a bar in Yukon that serves a “Sourtoe cocktail”. It consists of a shot of whisky with a human toe floating in the glass. An estimated 60,000 people have had it.",
"The Stockholm archipelago has more islands than the Pacific Ocean at around 30,000.",
"Pope Francis has been given many extravagant gifts over the years, and one of them was a Harley-Davidson motorcycle. However, rather than keeping it for his own pleasure and adventures, he sold it off and used the money to benefit homeless people.",
"In Japan, Domino’s started testing pizza delivery via reindeer in 2016.",
"The motto on the United Kingdom’s Royal Coat of Arms is in French. The motto is “Dieu t mon droit”, which means “God and my right”.",
"The average household income of the top 1% in the United States is $1,260,508 per year.",
"Disney sold the streaming right for the original Star Wars films in 2016 to Turner until 2024. Disney has since decided to start a streaming service and has tried asking for the rights back, but Turner refuses every time.",
"Gaming-related accidents increased by 26.5% during the first 5 months of Pokémon Go being released. This included 2 deaths and $25.5 million in damages.",
"Helen Keller was related to Robert E. Lee. Her paternal grandmother was second cousins with him.",
"During the 1908 Olympics in London, the Russians showed up 12 days late due to the fact that they were using the Julian calendar instead of the Gregorian calendar.",
"Non-violent attempts to escape Mexican prisons are not punished because “it’s human nature to want freedom”.",
"The line, “Born and raised in South Detroit” in Journey’s “Don’t Stop Believin” actually refers to Canada, not Michigan.",
"On one slow news day on April 18, 1930, a BBC radio announcer blatantly said “there is no news”",
"If you cut a starfish, it won’t bleed – it doesn’t have blood! Rather, they circulate nutrients by using seawater in their vascular system.",
"12% of the world’s total languages are found in Papua New Guinea, which has over 820 indigenous languages. There are more languages on this island than in any other country.",
"The hottest temperature ever recorded in Washington state was at Ice Harbor Dam at 118 °F (47.8 °C) on August 5, 1961.",
"In efforts to undercut the Dreamcast’s sales of the upcoming SEGA release, Sony announced the PlayStation 2 and exaggerated its performance capabilities.",
"Nepal has the most mathematical flag in the world. It even has an article in its constitution that details the steps of drawing the flag.",
"Mount Rushmore cost less than one million dollars to construct. It took 14 years to build – from 1927 to 1941 and took 400 workers.",
"Samsung means “three stars” in Korean. This was chosen by the founder because he wanted the company to be powerful and everlasting like stars in the sky.",
"On average, 46.1% of Americans have less than $10,000 in assets when they die.",
"While shedding, geckos will eat their skin in order to prevent predators from finding and eating them more easily.",
"Bees actually have knees. The expression comes from the fact that they store large build-ups of pollen in hairy baskets on their knees.",
"Between North and South Korea lies 155 miles of no man’s land where hundreds of rare animal species thrive.",
"While watching a Merry-Go-Round from a bench in Griffith Park, Los Angeles, Walt Disney was struck with inspiration for the creation of Disneyland.",
"There is a Scottish tartan designed for Mars exploration. It was officially registered in 2016 to be worn during Mars science, exploration and outreach activities.",
"Santa Claus was issued a pilot’s license from the U.S. government in 1927. They also gave him airway maps and promised to keep the runway lights on.",
"When you exercise, the burned fat metabolizes to become carbon dioxide, water, and energy. Meaning: you exhale the fat that you lose.",
"The word “velociraptor” comes from the Latin words “velox” which means swift, and “raptor” which means robber. Literally – speedy robber!",
"The largest stadium in the world is the Rungrado 1st of May Stadium in North Korea. It can hold up to 114,000 spectators. It covers 51 acres and is 197 feet tall.",
"Polar bears often hunt walruses by simply charging at a group of them and eating the ones that were crushed or wounded in the mass panic to escape. Direct attacks are rare.",
"The group of spikes at the end of stegosaurid tails are called the “thagomizer”. They had no distinct name until the term was coined in 1982 by a cartoonist.",
"There is a correlation between pulling an all-nighter and snapping out of depression. This is because the brain gets more active the longer it goes without sleep.",
"Adult cats only meow at humans, not other cats. Kittens meow to their mother but once they get a little older, cats no longer meow to other cats.",
"When shuffling a deck of cards, the number of possible arrangements is approximately 8×1067. That’s more than the number of stars in the observable universe.",
"There is a United Arab Emirates’ territory inside an Oman’s territory that itself is inside the United Arab Emirates country. It is called Madha village.",
"Disppointment Island is an uninhabited island in New Zealand. Over 65,000 pairs of white-capped albatross live there. In 1868, a steel tanker crashed on the island which killed 68 people, leaving the 15 survivors waiting 18 months to be rescued. In 1907, another ship ended up crashing there and 12 men drowned.",
"During the entire run of Gilligan’s Island, it was never revealed if “Gilligan” was his first or last name."]


f1 = random.randint(0,len(Fact))
def fact():
    return Fact[f1]